### ISSUE TITLE
Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by MuhammadSaudKhan** [itsrts/pptviewer-android#27]
I am facing this issue 
Caused by: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.di: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

	Caused by: com.android.tools.r8.internal.di: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

	Caused by: [CIRCULAR REFERENCE: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3]

**Comment by MuhammadSaudKhan** [comment]
When I update the minmum sdk to 21 above error is removed. Now I am facing following issue.
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: E:\AndroidStudioProjects\example projects\new_ppt_viewer\app\libs\itsrts-pptviewer.jar:com/olivephone/office/powerpoint/f/bi.class
	at Version.fakeStackEntry(Version_3.2.60.java:0)
	at com.android.tools.r8.internal.bi.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:68)
	at com.android.tools.r8.internal.bi.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:28)
	at com.android.tools.r8.internal.bi.a(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:27)
	at com.android.tools.r8.internal.bi.b(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:3)
	at com.android.tools.r8.D8.run(R8_3.2.60_61a204e00a4460bee78ec2913234dc5e1a3a501d9754e757835d117b7e302ba3:11)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:115)
	... 27 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by CandyTek** [comment]
I'm also stuck at this place, I don't know how to compile it smoothly.
